### ISSUE TITLE
Add a link for code

### ISSUE THREAD

**Issue by csm9493** [jhairgallardo/awesome-continual-self-supervised-learning#2]
Hi.

I have updated the official code of Regularizing with Pseudo-Negatives for Continual Self-Supervised Learning (ICML2024).
Could you add this GitHub (https://github.com/csm9493/PNR) as the code of it?

Thank you.
Sungmin Cha

**Comment by jhairgallardo** [comment]
Hi.

Thank you for sharing the code! I have added it to the list.

Best,
Jhair Gallardo
