### ISSUE TITLE
Consider adding paper

### ISSUE THREAD

**Issue by SkrighYZ** [jhairgallardo/awesome-continual-self-supervised-learning#3]
Hey Jhair, could you add "Integrating present and past in unsupervised continual learning" (CoLLAs 2024) to the list?

paper: https://arxiv.org/abs/2404.19132
code: https://github.com/SkrighYZ/Osiris

Thanks!

**Comment by jhairgallardo** [comment]
Hi,

Great paper! I have added it. 
I will update the list one of these days. I am pretty sure I am missing some works in 2024.

Best,
Jhair
